"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.
    */
    return queryInterface.bulkInsert(
      "Places",
      [
        {
          lat: 24.321845,
          lon: -110.325315,
          place_number: "Zona 1",
          capacity: 7,
          palm_roof: true,
          handicapped_seats: 0,
        },
        {
          lat: 24.321874,
          lon: -110.3252,
          place_number: "Zona 2",
          capacity: 7,
          palm_roof: true,
          handicapped_seats: 0,
        },
        {
          lat: 24.321901,
          lon: -110.325085,
          place_number: "Zona 3",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321911,
          lon: -110.324959,
          place_number: "Zona 4",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 3,
        },
        {
          lat: 24.321928,
          lon: -110.324862,
          place_number: "Zona 5",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 3,
        },
        {
          lat: 24.321916,
          lon: -110.324768,
          place_number: "Zona 6",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 3,
        },
        {
          lat: 24.321926,
          lon: -110.324637,
          place_number: "Zona 7",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321926,
          lon: -110.324503,
          place_number: "Zona 8",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321913,
          lon: -110.324411,
          place_number: "Zona 9",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321903,
          lon: -110.324326,
          place_number: "Zona 10",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321877,
          lon: -110.324248,
          place_number: "Zona 11",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321848,
          lon: -110.324177,
          place_number: "Zona 12",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321811,
          lon: -110.3241,
          place_number: "Zona 13",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321785,
          lon: -110.324024,
          place_number: "Zona 14",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321737,
          lon: -110.323934,
          place_number: "Zona 15",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321695,
          lon: -110.323842,
          place_number: "Zona 16",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321653,
          lon: -110.32375,
          place_number: "Zona 17",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321603,
          lon: -110.323656,
          place_number: "Zona 18",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321565,
          lon: -110.323586,
          place_number: "Zona 19",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321525,
          lon: -110.323511,
          place_number: "Zona 20",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.321483,
          lon: -110.323441,
          place_number: "Zona 21",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.32143,
          lon: -110.323367,
          place_number: "Zona 22",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
        {
          lat: 24.32138,
          lon: -110.323294,
          place_number: "Zona 23",
          capacity: 7,
          palm_roof: false,
          handicapped_seats: 0,
        },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Places", null, {});
  },
};
